### ISSUE TITLE
how to get icon columns sorted?

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#30]
This is actually a how-to question, as I've realized that if a particular table column contains only font-awesome icons (no text allowed in the cells), the regular sorting does not work. Is there a way to get such column sorted in sematable? Note: I've tried doing this reusing the answer suggested in http://stackoverflow.com/questions/25034503/sorting-a-table-with-columns-composed-of-icons but it did not work (moreover, I get an infinite loop :-().

**Comment by amir-hadzic** [comment]
Hi,

For such cases I usually use a value-based column with a custom component (that renders an icon based on the value). The actual value of the column is a number, string, or a boolean so the sorting should work. Does that make sense? 

Can you post a code example of what you are doing, and I'll take a closer look?

**Comment by pgoldweic** [comment]
Thanks Amir,
What I'm doing is simply render an icon in the column if some condition is true (that a value has been changed in an editable cell), so my table render includes the following line for the cell:

    <td className="narrowfield"><i className={changedCellClassname} aria-label={ariaChangedLabel}/>

and here's the preparatory code:
    const changedCellClassname = thisvalue !== originalValue ? "fa fa-asterisk fa-fw" : ""
    const ariaChangedLabel = thisgrade !== originalValue ? "changed" : ""

How would you give a value to the column? I've tried adding a <span> element in the same <td> with an associated value of "Yes" or "No" but unfortunately somehow this got me into an infinite rendering loop :-(. Would love to see your specific suggestion. Thanks!

**Comment by amir-hadzic** [comment]
Hi @pgoldweic,

Here's how I would do that. In the data I provide to the table there should be a field with true/false value. It doesn't matter if this field is part of original data, or if it's a computed field (with something like [reselect](https://github.com/reactjs/reselect)). I would define a column for this field, and use a custom YesNo component that renders "Yes" or "No" depending on field value.

The column definition would look like this:

```javascript
{
  key: 'confirmed',
  header: 'Confirmed',
  Component: YesNo,
  sortable: true,
}
```

We actually have an example in stories that uses this, so you can take a look at [YesNo component](https://github.com/sematext/sematable/blob/master/stories/common/YesNo.js) as well. This is used in the [UsersTable](https://github.com/sematext/sematable/blob/master/stories/common/UsersTable.js) example.

That's it, since the column is marked as sortable, and it has a true/false value, it should be possible to click on the header to sort by that column.

I hope that helps!

**Comment by pgoldweic** [comment]
An update: turns out that now that I've added the extra 'changed' boolean field to my data objects, using my original code *does* in fact sort the icon column, without the need to use any other component to render the icon. 
So I've gone back to render the field as follows:

    <td className="narrowfield"><i className={changedCellClassname} /></td>

where changedCellClassname is either "" or "fa fa-asterisk fa-fw" depending on the value (the second is what's needed to render the icon).
And this is in fact now sorting the column!  Can you tell what is that makes this code work but the one above  (with the YesNo component) not? 

Anyway, thanks for suggesting that I added the additional field. I think this probably was the key to the solution.
