### ISSUE TITLE
Table without Primary key

### ISSUE THREAD

**Issue by sreevisakh** [sematext/sematable#68]
My table have composite key, is there an api available which will accept a function to generate primaryKey from the given data, Or automatically take the index as the primary key?

**Comment by mbonaci** [comment]
Hi @sreevisakh, it's currently not possible to provide a function that generates primary keys, but we would be willing to accept a PR that composes multiple `primaryKey=true` column `key`s into a composite key.
Here's how we get primary key:
https://github.com/sematext/sematable/blob/e7a565b2beded14969d8f1e02c550e33e9861beb/src/reducer.js#L48
So you'd have to use `filter` instead of `find` and then handle composition of multiple columns, if found.

But let's first see whether the Sematable author, @amir-hadzic will agree with me.
There may be some unintended consequences that I'm not seeing.

**Comment by amir-hadzic** [comment]
Hi @sreevisakh. The reason why we need the primary key defined outside sematable is because of the select row functionality. In react apps data can often change, and sematable itself will rearrange data by sorting and filtering, so index is not a reliable way to track selected rows.

This is why we've decided to move the responsibility of uniquely identifying rows to the user. The easiest solution in your case would be to enrich the data with the composite key as another property before passing it to sematable. A library like [reselect](https://github.com/reactjs/reselect) would probably help in doing that.

Adding support for composite keys sounds OK to me. And yes, one of the changes that would need to be done is what @mbonaci already mentioned. There are probably other places that need to be updated though, along with the README. I'll create another issue for implementing composite keys.
