### ISSUE TITLE
How can we use SemaTable using MaterialUi Components 

### ISSUE THREAD

**Issue by sanjayagnani92** [sematext/sematable#79]
How can we use SemaTable wrapper using Material UI -Next Components  

Which all components need to need rewritten,

**Comment by mbonaci** [comment]
I'm not sure what are the requirements for integrating MaterialUI, but you can look at our code to see which components accept a `className` or `style` or `styleName` prop (or inherit all parent's props) in order to see whether that allows you to override component's style.  

If you see a blocker you can comment here and we'll take a look.
